### PR TITLE
Update Readme to reflect new Klipper syntax

### PR DESCRIPTION
**Pull request by soxhi8**
Klipper received a breaking change on setting default parameters lately, so the macro needs to be updated.
https://github.com/Klipper3d/klipper/issues/4864

### CODE REVIEW

**Comment by fieldOfView** [comment]
Does this need a note about which versions of Klipper need which syntax, or does the new syntax work for all versions?

**Comment by soxhi8** [comment]
I will check compatibility for older versions and report back once I know more.

**Comment by jjgraphix** [comment]
I can confirm the proposed syntax should have no issues in any documented Klipper version that supports macros. Anything prior to this wouldn't be relevant anyway.

If it's helpful, to avoid macros and resolve other compatibility issues like multiple extruders, I remixed your work into an unofficial [PressureAdvanceSettingPlugin](https://github.com/jjgraphix/PressureAdvanceSettingPlugin) for _Klipper only_. I've continued development for my own curiosity but some of my changes might help if you decide to focus on Klipper support. It may not be worth it but perhaps a _Klipper Firmware Support_ sub-setting would be a workaround to getting this fully compatible, unless you convince the devs to add a klipper g-code flavor :).

**Comment by fieldOfView** [comment]
I don't know why I never merged this, but better late than never, I guess.

**Comment by soxhi8** [comment]
> I don't know why I never merged this, but better late than never, I guess.

You were likely waiting for more confirmation on compatibility on older versions of Klipper, which I did not get around to testing in detail. But as jigraphix said, it should not be an issue. Thanks for merging!

**Pull request merged**
