### PR TITLE
Initial Culture support

### PR DESCRIPTION
**Pull request by GMagician**
This start adding Culture to addin. Missing how to extract from cura current language

Any hint?

### CODE REVIEW

**Comment by fieldOfView** [comment]
I appreciate the effort you put into this, but I will not create a new translation system that competes with what is already available in Cura.

**Comment by fieldOfView** [comment]
I am working on getting the standard i18n translation system in Cura working with this plugin. This works with .pot "templates" and .po "translations" like the rest of Cura and some other plugins. It is still early days, but I am closing this PR because your approach is not compatible with that approach.

Again, thanks for the work you put into this. I will see if I can reuse your translation strings in the new i18n system.

**Comment by GMagician** [comment]
Ok, I'm sorry but I don't know how Cura/i18n work so this was my only possible approach

**Comment by GMagician** [comment]
If you wish, giving me some hint, I can try to continue on the right way

**Comment by fieldOfView** [comment]
Check out the master branch. Then use [poedit](https://poedit.net) or similar to create a new .po translation from the `linearadvancesettingplugin.pot` template. Put it in a new folder inside the `i18n` folder, named after the language (eg `i18n/it_IT/linearadvancesettingplugin.po`). Then create a PR,

**Pull request closed without merging**
